#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <string.h>

int main() {
    // Create a child process
    pid_t pid = fork();

    if (pid == -1) {
        perror("Error forking process");
        exit(1);
    }

    if (pid == 0) 
	{
        // Child process: run the myRand program
        execl("./myRand", "myRand", (char *) NULL);
        perror("Error executing myRand");
        exit(1);
    }

    // Parent process: wait for the child process to finish
    int status;
    wait(&status);

    // Get the exit status of the child process
    int exit_status = WEXITSTATUS(status);

    // Open the file generated by myRand
    int fd = open("dataX.dat", O_RDONLY);
    if (fd == -1) {
        perror("Error opening file");
        exit(1);
    }

    // Read the values from the file and compute their average
    int sum = 0;
    int values[60];
    char buffer[10];
	int bRead;
	int index = 0;
    while ((bRead = read(fd, buffer, 10)) > 0)
	{
		//null termiante buffer
		buffer[bRead] = '\0';
		//set values to seperate tokens to be converted
		char* token = strtok(buffer, " ");
		while(token != NULL)
		{
			values[index] = atoi(token);
			sum += values[index];
			index++;
			token = strtok(NULL, " ");
		}
	}

    // Close the file
    close(fd);

    // Display the values and their average
    printf("Values: \n");
    for (int i = 0; i < 60; i++)
	{
        printf("%d\n ", values[i]);
    }
    printf("\n");
    double average = (double) sum / 60;
    printf("Average: %.2f\n", average);

    // Unlink the file
    unlink("dataX.dat");

    return 0;
}